### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by christopheremv** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-christopheremv#1]
[Realidad aunmentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-christopheremv/files/10808019/Realidad.aunmentada.pdf)

**Comment by bg55-a** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho
